# Generated by Django 5.2.5 on 2025-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="no_of_seats",
            field=models.PositiveBigIntegerField(default=30),
            preserve_default=False,
        ),
    ]
