# Generated by Django 5.2.5 on 2025-08-27 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking"),
        ("bookings", "0004_create_admin_user"),
    ]

    operations = []
